on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  VULTR_REGISTRY: sjc.vultrcr.com
  VULTR_IMAGE_NAME: seven/bird-lg-go
  GHCR_IMAGE_NAME: bird-lg-go

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      proxy: ${{ steps.filter.outputs.proxy }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Detect Changed Paths
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            frontend:
              - 'frontend/**'
            proxy:
              - 'proxy/**'

  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/setup-go@v5

      - name: Run Frontend Unit Test
        run: |
          export GO111MODULE=on
          cd frontend
          go get -v -t -d ./...
          go test -v ./...
          cd ..

      - name: Run Proxy Unit Test
        run: |
          export GO111MODULE=on
          cd proxy
          go get -v -t -d ./...
          go test -v ./...
          cd ..

  docker-test:
    runs-on: ubuntu-latest
    needs:
      - changes
    if: needs.changes.outputs.frontend == 'true' || needs.changes.outputs.proxy == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Test whois Binary in Frontend Image
        if: needs.changes.outputs.frontend == 'true'
        run: |
          docker build -t local/frontend frontend/
          docker run --rm --net host --entrypoint whois local/frontend -I github.com || exit 1
          docker run --rm --net host --entrypoint whois local/frontend -h whois.ripe.net github.com || exit 1
          docker run --rm --net host --entrypoint whois local/frontend -h whois.ripe.net:43 github.com || exit 1

      - name: Test traceroute Binary in Proxy Image
        if: needs.changes.outputs.proxy == 'true'
        run: |
          docker build -t local/proxy proxy/
          docker run --rm --net host --entrypoint traceroute local/proxy 127.0.0.1 || exit 1
          docker run --rm --net host --entrypoint traceroute local/proxy ::1 || exit 1

      - name: Test mtr Binary in Proxy Image
        if: needs.changes.outputs.proxy == 'true'
        run: |
          docker build -t local/proxy:mtr -f proxy/Dockerfile.mtr proxy/
          docker run --rm --net host --entrypoint mtr local/proxy:mtr -w -c1 -Z1 -G1 -b 127.0.0.1 || exit 1
          docker run --rm --net host --entrypoint mtr local/proxy:mtr -w -c1 -Z1 -G1 -b ::1 || exit 1

  docker-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    needs:
      - go-test
      - docker-test
      - changes
    if: github.event_name != 'pull_request' && (needs.changes.outputs.frontend == 'true' || needs.changes.outputs.proxy == 'true')
    steps:
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login in to Vultr Container Registry
        id: vultr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.VULTR_REGISTRY }}
          username: ${{ secrets.VULTR_USERNAME }}
          password: ${{ secrets.VULTR_PASSWORD }}

      - name: Log in to GitHub Container Registry
        id: ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build - Frontend
        id: frontend
        if: needs.changes.outputs.frontend == 'true'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:frontend"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:frontend-dev
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:frontend-dev-${{ github.sha }}
            ghcr.io/realsunyz/bird-lg-go:frontend-dev
            ghcr.io/realsunyz/bird-lg-go:frontend-dev-${{ github.sha }}

      - name: Generate Artifact Attestation (OCI Referrers) - Frontend
        id: attest-frontend
        if: needs.changes.outputs.frontend == 'true'
        uses: actions/attest-build-provenance@v3
        continue-on-error: true
        with:
          subject-name: ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}
          subject-digest: ${{ steps.frontend.outputs.digest }}
          push-to-registry: true

      - name: Build - Proxy
        id: proxy
        if: needs.changes.outputs.proxy == 'true'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:proxy"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:proxy-dev
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:proxy-dev-${{ github.sha }}
            ghcr.io/realsunyz/bird-lg-go:proxy-dev
            ghcr.io/realsunyz/bird-lg-go:proxy-dev-${{ github.sha }}

      - name: Generate Artifact Attestation (OCI Referrers) - Proxy
        id: attest-proxy
        if: needs.changes.outputs.proxy == 'true'
        uses: actions/attest-build-provenance@v3
        continue-on-error: true
        with:
          subject-name: ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}
          subject-digest: ${{ steps.proxy.outputs.digest }}
          push-to-registry: true

      - name: Build - Proxy (MTR)
        id: proxy-mtr
        if: needs.changes.outputs.proxy == 'true'
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:proxy"
          file: "Dockerfile.mtr"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:proxy-dev-mtr
            ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}:proxy-dev-mtr-${{ github.sha }}
            ghcr.io/realsunyz/bird-lg-go:proxy-dev-mtr
            ghcr.io/realsunyz/bird-lg-go:proxy-dev-mtr-${{ github.sha }}

      - name: Generate Artifact Attestation (OCI Referrers) - Proxy (MTR)
        id: attest-proxy-mtr
        if: needs.changes.outputs.proxy == 'true'
        uses: actions/attest-build-provenance@v3
        continue-on-error: true
        with:
          subject-name: ${{ env.VULTR_REGISTRY }}/${{ env.VULTR_IMAGE_NAME }}
          subject-digest: ${{ steps.proxy-mtr.outputs.digest }}
          push-to-registry: true
